apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-configmap.yaml
  - secret-store.yaml
  - external-secret.yaml
  - backend-hpa.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-configmap.yaml
  - ingress.yaml
